name: buildx

on:
  push:
    branches:
      - "*"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx args
        id: setup_docker_buildx_args
        run: |
          DOCKER_IMAGE=bxggs/nginx-video
          DOCKER_PLATFORMS=linux/amd64,linux/arm64

          BRANCH=${GITHUB_REF#refs/heads/}

          if [[ "$BRANCH" == "master" ]]; then
            DOCKER_TAG_PRETTY=latest
          else
            DOCKER_TAG_PRETTY=$BRANCH
          fi

          DOCKER_TAG_SHA=$GITHUB_SHA

          BUILDX_ARGS="-t \"$DOCKER_IMAGE:$DOCKER_TAG_PRETTY\" -t \"$DOCKER_IMAGE:$DOCKER_TAG_SHA\" --platform \"$DOCKER_PLATFORMS\" ."

          echo "::set-output name=buildx_args::$BUILDX_ARGS"
      - name: Setup Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Build Docker images
        run: docker buildx build --output "type=image,push=false" ${{ steps.setup_docker_buildx_args.outputs.buildx_args }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push Docker images
        run: docker buildx build --output "type=image,push=true" ${{ steps.setup_docker_buildx_args.outputs.buildx_args }}
