name: test_build
on:
  push:
    branches_ignore:
      - master
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test build
        run: docker build -t test-build .
